services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: audio-segmentation-db
  - type: web
    name: frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm install serve -g && serve -s build -l 3000
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: http://localhost:8000
